download:
  n_locs: null
  locs: [99999994992,99999994993,99999994994,99999994995,99999994996]
  year: 2003

prepare:
  monthly_fields: ['MonthlyMaximumTemperature', 'MonthlyMinimumTemperature']
  daily_fields: ['DailyMaximumDryBulbTemperature', 'DailyMinimumDryBulbTemperature']
